const getBanters = async () => {
  let banters = ["&nimi& mene töihin.",
  "Haista &nimi& paska.",
  "&nimi& anna muidenkin puhua.",
  "&nimi& 🖕",
  "&nimi& ur mom gay :D",
  "&nimi& senkin tymähpää",
  "&nimi& suihkuun, nukkumaan ja aamulla töihin. Muuta neuvoa ei tule.",
  "&nimi& hommaa muija",
  "Onko paavilla parvele &nimi&?! Onko? Hä!?",
  "&nimi& jos ei ole mitään fiksua sanottavaa, voi pitää turpansa kiinni.",
  "&nimi& on kuningas.",
  "Kiitos, olet hieno ihminen &nimi&",
  "Juho on tyhmä, eikö vain &nimi&?",
  "&nimi&, pelataanko Pomppaa?",
  "Kiitos &nimi&, mielipiteesi on tärkeä :)",
  "Vedä vittu päähän ja painu Norjaan &nimi&!",
  "&nimi& etsi joku muu joka susta vois kiinnostuu",
  "&nimi& tänään vedetään kännit, ja oksennellaan ympäriinsä🇪🇸",
  "EZ4&nimi&",
  "&nimi&, haluaisin oksentaa pilluusi",
  "&nimi&, voisinko lipaista pyllynreikääsi?",
  "slurps splurp &nimi& on janu",
  "olen väsinud, pehme &nimi&",
  "Tissit tiskiin &nimi&",
  "meinasko &nimi& painaa pimpotinta tänään?",
  "Onko &nimi& darra?",
  "&nimi&, otitko sä simaa?",
  "Pylly paljaaks ja paljuun, &nimi&!",
  "Täytyykö paljussa todellakin olla alapää paljaana, &nimi&?",
  "Anteeksi &nimi&, nyt en ymmärrä?",
  "Rohkenen olla erimieltä &nimi&.",
  "Pitäisikö laittaa puhelin kiinni &nimi&?",
  "&nimi& sun äiti on ihan mukava😉",
  "&nimi&, tollpahyppy",
  "Muista &nimi&, ei tippa tapa😉",
  "Eihän se keltään ole pois, eihän &nimi&?",
  "&nimi&, olisikohan aika mennä nukkumaan?",
  "&nimi& hei sun täytyy muuttuu. Sun elämältä suuntaa puuttuu.",
  "&nimi& mitä jos lopettaisit tai edes vähentäisit.",
  "&nimi& söi lapsen vanukkaat."
];

  return banters
}

module.exports = getBanters;