name: Daily comic

on:
  schedule:
    - cron: "*/5 * * * *"

jobs:
  send-comics:
    runs-on: ubuntu-latest
    steps:
      - name: HTTP Request Action
        uses: fjogeleit/http-request-action@v1.4.1
        with:
          url: '${{ secrets.BOT_URL }}/timed'
          method: 'GET'
          timeout: 10000